services:
  ingest-api:
    build: .
    container_name: ingest_api
    ports:
      - "8000:8000"
    env_file:
      - .env  # carga tus variables de entorno
    volumes:
      # 🔹 Monta tu código local (ya lo tienes bien)
      - .:/app
      # 🔹 Monta tus credenciales AWS para poder subir a S3
      - ~/.aws:/root/.aws:ro
      # 🔹 (Opcional) Monta la ruta NFS donde está el SQLite
      #   Solo si tu /mnt/theaters en el host apunta al NFS correcto
      - /mnt/theaters:/mnt/theaters:ro
    restart: unless-stopped
